### ISSUE TITLE
Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0

### ISSUE THREAD

**Issue by h4num4n-nomads** [Sifir-io/react-native-tor#15]
Hello, 

I cant use this tool in a new project.

Just make a new project with: `react-native init projectname`
And then install the react-native-tor with `npm i react-native-tor`

After this using : `npx react-native run-android`

I get this error:

`Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.2/userguide/command_line_interface.html#sec:command_line_warnings
26 actionable tasks: 19 executed, 7 up-to-date
repository\x\android\app\src\debug\AndroidManifest.xml Error:
        uses-sdk:minSdkVersion 16 cannot be smaller than version 26 declared in library [sifir_android.aar] C:\Users\x\.gradle\caches\transforms-2\files-2.1\d1b53437b9b544e7ed30bf7073aa64ea\sifir_android\AndroidManifest.xml as the library might be using APIs not available in 16
        Suggestion: use a compatible library with a minSdk of at most 16,
                or increase this project's minSdk version to at least 26,
                or use tools:overrideLibrary="com.sifir.tor" to force usage (may lead to runtime failures)`

Node version: 15.5.1
Npm version: 7.3.0
ReactNative version: 4.13.1
Windows: 10

Note: if I run `npx react-native run-android` without installing `npm i react-native-tor` the project load in the emulator without any problem.

**Comment by gabidi** [comment]
```
... Suggestion: use a compatible library with a minSdk of at most 16, or increase this project's minSdk version to at least 26
```
In `android/build.gradle` around line ~6
`minSdkVersion = 16 ` change it to `minSdkVersion = 26`
