### ISSUE TITLE
Network disconnect is not handled well (Socket, android)

### ISSUE THREAD

**Issue by Overtorment** [Sifir-io/react-native-tor#16]
Typical situation is when network disappears and reappears in a while (say, a couple of mins). This can be easily reproduced on your development laptop by disabling wifi for a couple of mins and then enabling it.

I did tests of this scenario with android emulator and my typical reconnection routine for sockets didn't work well with this lib.
What I usually do is: when I detect socket error (issued during socket write, for example, or ping timeouts), I try to end (or close) socket, and then reconnect. If reconnect is not successful - try again and again indefinitely, with some delay.

This is not working well with this lib: first, `tor.createTcpConnection()` doesn't have any timeout and can hang forever. Even if network appears.
What I usually do in such cases if `Promise.race`:

```js
      await tor.startIfNotStarted();
      const iWillConnectISwear = tor.createTcpConnection({ target: host + ':' + port }, (data, err) => {
      ...
      }

      try {
        this._socket = await Promise.race([iWillConnectISwear, new Promise(resolve => setTimeout(resolve, 21000))]);
      } catch (e) {}

      if (!this._socket) {
        console.log('connecting TOR socket failed'); // either sleep expired or connect threw an exception
        return false; // CONNECTION RETRY WILL HAPPEN
      }
```

As you can see, we are waiting for 21sec for `createTcpConnection` promise to resolve. If it didn't resolve, we return FALSE and outer code will re-attempt in a couple of seconds.

I occasionally had success with this approach and this lib, but not consistently. If you simulate network disruption 3 times in a row, this might not work and reconnect socket all 3 times. Or, it might claim co connect but the resulting socket object is defunct, can't get any data out of it.

What can we do about it?

**Comment by gabidi** [comment]
Thanks for the feedback @Overtorment !
 I think adding a timeout parameter for `createConnection` is a reasonable request and relatively easy win.
Will get on it .

**Comment by Overtorment** [comment]
any progress on this?

**Comment by gabidi** [comment]
> any progress on this?

Unfortunately had zero time this past week. Hopefully I can give it a ago this week. Will update you.
