### ISSUE TITLE
Socket interface?

### ISSUE THREAD

**Issue by Overtorment** [Sifir-io/react-native-tor#2]
Made it work with plain GET requests to onion endpoints successfully, but reading docs and `lib/typescript/src/index.d.ts` I cant find any methods to do raw socket interaction.
That would be useful to connect to electrum servers through TOR  (example list of servers https://1209k.com/bitcoin-eye/ele.php )

**Comment by gabidi** [comment]
In TODO list. 
Would you have a link to a regular non proxied Websocket JS client connecting and consuming the data? 
Would help in designing the native side of things. Thanks for this.

**Comment by Overtorment** [comment]
As far as I understand, websockets have nothing to do with it. Just plain tcp sockets.

We in Bluewallet use this package: https://github.com/Rapsssito/react-native-tcp-socket
Socket interface like in nodejs would work too: https://nodejs.org/api/net.html#net_class_net_socket


Example socket usage in Bluewallet: https://github.com/BlueWallet/BlueWallet/blob/master/blue_modules/BlueElectrum.js and https://github.com/BlueWallet/rn-electrum-client/blob/master/lib/client.js



BTW, electrum protocol is brain-dead simple and can be used to debug socket functionality. For example, you can just connect to electrum's socket (via clearnet or tor, whatever) and send `{"id": 1, "method": "blockchain.scripthash.get_balance", "params": ["716decbe1660861c3d93906cb1d98ee68b154fd4d23aed9783859c1271b52a9c"]}\n` and you will immediately get a response from server , like `{"jsonrpc": "2.0", "result": {"confirmed": 51432, "unconfirmed": 0}, "id": 1}`

Heres a console oneliner I use to check if some electrums server works:

```bash
echo '{"id": 1, "method": "blockchain.scripthash.get_balance", "params": ["716decbe1660861c3d93906cb1d98ee68b154fd4d23aed9783859c1271b52a9c"]}' | timeout 2 nc electrum1.bluewallet.io  50001 -i 1
```

**Comment by gabidi** [comment]
That's very helpful thanks, will look into it this weekend.

**Comment by gabidi** [comment]
So doing:
```sh
[homebase]$ echo '{"id": 1, "method": "blockchain.scripthash.get_balance", "params": ["716decbe1660861c3d93906cb1d98ee68b154fd4d23aed9783859c1271b52a9c"]}' | timeout 10 netcat -x localhost:19054 udfpzbte2hommnvag5f3qlouqkhvp3xybhlus2yvfeqdwlhjroe4bbyd.onion 60001 -i 1
{"id":1,"jsonrpc":"2.0","result":{"confirmed":51432,"unconfirmed":0}}
````
on a local machine running the sifir-rs-sdk (Tor daemon with socks proxy on port 19054) and it seems to have connected and received a response from a onion server chosen from the list in the link provided.

So the socks proxy successfully forwards TCP requests to the server ✔️ 

The only question that remains is can the package being used by Bluewallet use the socks proxy....

**Comment by Overtorment** [comment]
no it cannot, and I doubt it ever will (https://github.com/Rapsssito/react-native-tcp-socket/issues/80). other socket packages for react-native don't support socks proxies as well. 

there are pure js implementations of socks proxies, but it is kind of a big project on its own, so it would be a pain in the ass to add it.

**Comment by gabidi** [comment]
I see, Will look into making this part of the library.

**Comment by 4l3ss** [comment]
Hi here is how I did it in JS. I implemented some parts of the SOCKS5 protocol which is very straight forward (https://en.wikipedia.org/wiki/SOCKS#SOCKS5) to connect to electrum servers through the TOR proxy provided by this library. 
You may find some parts of these files interesting :
https://github.com/Satpile/satpile/blob/master/utils/TcpClient.ts
https://github.com/Satpile/satpile/blob/master/utils/explorers/ElectrumClient.ts
https://github.com/Satpile/satpile/blob/master/utils/explorers/Electrum.ts

Please understand that I didn't fully implement every specifications of the SOCKS5 protocol nor the electrum protocol, I only wrote the parts I needed for that project, but I think it may help someone wanting to do something similar.

**Comment by gabidi** [comment]
Awesome thanks for the info!
I had already started implementing the tcp communication (msg + reply) in rust to keep it close to the bare bone and as portable as possible.
https://github.com/Sifir-io/sifir-rs-sdk/blob/feature/sockets-2/tor/src/lib.rs#L474-L498
Working now on the FFI for Android/IOS (most of the overhead has already been created for the previous milestones).
Should be ready soon (TM)

Will be checkout what you sent, Thanks!

**Comment by gabidi** [comment]
Handled by https://github.com/Sifir-io/react-native-tor/pull/12
