### ISSUE TITLE
Auditability: let users build library with reproducibly built Tor binaries

### ISSUE THREAD

**Issue by kaloudis** [Sifir-io/react-native-tor#22]
This way users can have more assurance of what the code is running.

Currently modules are precompiled:
android/libs/sifir_android.aar
ios/Libsifir_ios.framework/Libsifir_ios

**Comment by gabidi** [comment]
https://github.com/Sifir-io/react-native-tor#development-and-building-from-scratch

is that what you mean ?

**Comment by gabidi** [comment]
Closing issue. 

Let me know if further clarity/transparency is required. It's a very important to make sure all parts of this stack are reproducible independently.
