### ISSUE TITLE
whats the real minSdk? 

### ISSUE THREAD

**Issue by Overtorment** [Sifir-io/react-native-tor#29]
when I set 26  I get `java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "glob" referenced by`, but bumping it to 28 fixes the issue

**Comment by gabidi** [comment]
https://github.com/Sifir-io/react-native-tor/issues/36

**Comment by gabidi** [comment]
Closing since answered in #36 , please feel free to re-open if need be.
