### ISSUE TITLE
AndroidRuntime: java.lang.UnsatisfiedLinkError: dlopen failed: library "/data/app/~~0m29kOn8bv7hYTGOuPgwEA==/com.test5-AOw6KYwqt1Hq6Do9Vl2cqA==/lib/arm64/libsifir_android.so" not found

### ISSUE THREAD

**Issue by Oct4Pie** [Sifir-io/react-native-tor#31]
I have been trying to get my app to work, but there seem to be issues with ```libsifir_android.so```. The app works on iOS, but it fails on android every single time due to this error.
I have included ```implementation files("../../node_modules/react-native-tor/android/libs/sifir_android.aar")``` in ```android/app/build.gradle```. Another interesting part is that ```libsifir_android.so``` is present in the apk, in ```lib```, and I was able to find it in ```/data/data/<appName>/lib-main```. It somehow is not found by the app.
The error: ```AndroidRuntime: java.lang.UnsatisfiedLinkError: dlopen failed: library "/data/app/~~0m29kOn8bv7hYTGOuPgwEA==/com.test5-AOw6KYwqt1Hq6Do9Vl2cqA==/lib/arm64/libsifir_android.so" not found```
What could be going on in this case?
Operating System: macOS
react-native-tor version: ^0.1.7

**Comment by gabidi** [comment]
Hi, Thank you for reporting this.
What version of Android are you trying this on?

**Comment by Oct4Pie** [comment]
Thanks for your response.
I am using the ```Android 11.0 arm64-v8a (Pixel 5 API 30)``` emulator. I also tried `x86`, but it still had the same issue.
<img width="1058" alt="Screen Shot 2021-05-31 at 3 37 51 PM" src="https://user-images.githubusercontent.com/65843843/120246795-2af24b80-c226-11eb-8db7-33d9362b4d15.png">

**Comment by gabidi** [comment]
I just ran the included example app on a Pixel 5 sim and it ran fine.  Does the example app included in the repo (https://github.com/Sifir-io/react-native-tor/tree/main/example)  run on your simulator ? That would help in determining what kind of error we're looking at.

**Comment by Oct4Pie** [comment]
Yes, I was able to run the example in my simulator after some trouble, but my sample does not run.
I checked your example and saw that the `.so` libraries were installed properly, but they weren't in mine.

**Your example:**
```130|emulator_arm64:/data/app/~~tzL60GDD-uJwcfHoI9DRnQ==/com.example.reactnativetor-QP0OtVB_tTd7dUCsQvdiig== # ls lib/arm64
libc++_shared.so       libfbjni.so          libglog_init.so                libjsc.so             libnative-imagetranscoder.so
libevent-2.1.so        libflipper.so        libhermes-executor-debug.so    libjscexecutor.so     libreactnativeblob.so
libevent_core-2.1.so   libfolly_futures.so  libhermes-executor-release.so  libjsijniprofiler.so  libreactnativejni.so
libevent_extra-2.1.so  libfolly_json.so     libhermes-inspector.so         libjsinspector.so     libsifir_android.so
libfb.so               libglog.so           libimagepipeline.so            libnative-filters.so  libyoga.so```
Mine:
```emulator_arm64:/data/app/~~yZuOo1pLy5hFlqGE7UwHBQ==/com.test8-fvciJ-hiUD94pPtuzvzm0Q==/lib # ls arm64
emulator_arm64:/data/app/~~yZuOo1pLy5hFlqGE7UwHBQ==/com.test8-fvciJ-hiUD94pPtuzvzm0Q==/lib # ```
Instead, the libraries in my case are installed in `/data/data/`:
```emulator_arm64:/ # ls /data/data/com.test8/lib-main
dso_deps                     libhermes-executor-release.so
dso_lock                     libhermes-inspector.so
dso_manifest                 libimagepipeline.so
dso_state                    libjsc.so
libc++_shared.so             libjscexecutor.so
libevent-2.1.so              libjsijniprofiler.so
libevent_core-2.1.so         libjsinspector.so
libevent_extra-2.1.so        libnative-filters.so
libfb.so                     libnative-imagetranscoder.so
libfbjni.so                  libreactnativeblob.so
libflipper.so                libreactnativejni.so
libfolly_futures.so          libreanimated.so
libfolly_json.so             libsifir_android.so
libglog.so                   libturbomodulejsijni.so
libglog_init.so              libyoga.so
libhermes-executor-debug.so```
When I copied them to the right `lib` directory, the app worked fine.
I even removed all of my app's dependencies to be sure the issue is from this module.
My `App.js`:
```import React from "react";
import Tor from "react-native-tor";
import { SafeAreaView, Text } from "react-native";

const tor = Tor({
  // stopDaemonOnBackground: false,
});

class App extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      events: [],
    };
  }

  render() {
    return (
      <SafeAreaView>
        <Text>Test8</Text>
      </SafeAreaView>
    );
  }
}

export default App;
```

**Comment by gabidi** [comment]
- What's the minimum SDK and target SDK in your App ?
- What version of React Native are you on ?
- Just to confirm you added `implementation files("../../node_modules/react-native-tor/android/libs/sifir_android.aar")` to `android/app/build.gradle` ?

Also i'm curious when you say
`Yes, I was able to run the example in my simulator after some trouble...` 
Would you be kind to let me know what the trouble was ? Maybe it's something I need to fix or clarify in the instructions. Thanks!

**Comment by Oct4Pie** [comment]
- SDK and tools' versions:
```
ext {
        buildToolsVersion = "29.0.3"
        minSdkVersion = 26
        compileSdkVersion = 30
        targetSdkVersion = 30
}
```
- React Native version: `"react-native": "~0.63.4"`
- Yes, I added `implementation files("../../node_modules/react-native-tor/android/libs/sifir_android.aar")` to `android/app/build.gradle`
```
dependencies {
    implementation fileTree(dir: "libs", include: ["*.jar"])
    //noinspection GradleDynamicVersion
    implementation "com.facebook.react:react-native:+"  // From node_modules
    implementation "androidx.swiperefreshlayout:swiperefreshlayout:1.0.0"
    debugImplementation("com.facebook.flipper:flipper:${FLIPPER_VERSION}") {
      exclude group:'com.facebook.fbjni'
    }
    debugImplementation("com.facebook.flipper:flipper-network-plugin:${FLIPPER_VERSION}") {
        exclude group:'com.facebook.flipper'
        exclude group:'com.squareup.okhttp3', module:'okhttp'
    }
    debugImplementation("com.facebook.flipper:flipper-fresco-plugin:${FLIPPER_VERSION}") {
        exclude group:'com.facebook.flipper'
    }
    addUnimodulesDependencies()

    if (enableHermes) {
        def hermesPath = "../../node_modules/hermes-engine/android/";
        debugImplementation files(hermesPath + "hermes-debug.aar")
        releaseImplementation files(hermesPath + "hermes-release.aar")
    } else {
        implementation jscFlavor
    }

    implementation files('../../node_modules/react-native-tor/android/libs/sifir_android.aar')
}
```

I am using macOS, and encountered these errors during the setup for your example:
`java.lang.NoClassDefFoundError: Could not initialize class org.codehaus.groovy.vmplugin.v7.Java7`
fixed by `export JAVA_HOME="/Applications/Android Studio Preview.app/Contents/jre/Contents/Home"` (Android Studio JRE)

- `error SHA-1 for file /usr/local/lib/node_modules/react-native/node_modules/metro/src/lib/polyfills/require.js`
- `Module @babel/runtime/helpers/interopRequireDefault does not exist`
-  Plus Many other errors about JS libraries

All fixed by `npm install -i -g --force react-native-cli` or using `npx react-native start` instead of the outdated `react-native` and running `yarn`.

**Comment by gabidi** [comment]
Can you please up your projects `minSdkVersion` to at least `29` , reinstall deps and retry.
If that solves your problem I think i know what's going on.

**Comment by Oct4Pie** [comment]
I tried that along with a countless number of other ways. None of them worked, so I decided to modify the way `sifir_android` was loaded. I saw that it only was relying on the app's `lib` directory for it. I modified (in 
<img width="721" alt="Screen Shot 2021-06-09 at 2 16 10 AM" src="https://user-images.githubusercontent.com/65843843/121327839-aad48180-c8c8-11eb-964f-7a19bee7ead7.png">
`TorPackage.kt` file) `System.load("${ai.nativeLibraryDir}/libsifir_android.so");` to `System.loadLibrary("sifir_android");` so that it would search in `/data/data/<appName>/lib-main` as well. That was the only solution that worked!
I don't know if it is the right way to approach it still. Anyway, thanks for the help!

**Comment by gabidi** [comment]
hmmm I think originally I had it using `loadLibrary` but changed it due to changes in Sdk `29` and above:
https://github.com/Sifir-io/react-native-tor/blame/f7719a85a90bbdd6e8202764d84cedba47665084/android/src/main/java/com/reactnativetor/TorPackage.kt#L15
I think it was working fine on a simulator but would error out when compiled into an APK and run on a real world device.
In eithercase if it's working for you that's great ! 
Let me know if there's anything else I can help with otherwise please Feel free to close the issue :)

**Comment by Oct4Pie** [comment]
That makes sense. I will try other SDK versions as well later on.
Thank you very much for the guidance!

**Comment by Idan-Neeman** [comment]
@Oct4Pie Did you manage to solve that?

**Comment by Idan-Neeman** [comment]
@gabidi @Oct4Pie I get the same error... tried to use the loadLibrary, but the same error. I'm triyng to create a bundle of bluewallet and this library makes it fail...

**Comment by Oct4Pie** [comment]
What is the output of `logcat` on your device?
The same failing of dlopen?
