### ISSUE TITLE
Unable to compile with React Native 65

### ISSUE THREAD

**Issue by marcosrdz** [Sifir-io/react-native-tor#38]
https://github.com/BlueWallet/BlueWallet/pull/3607

Log:

> Task :react-native-tcp-socket:bundleLibCompileToJarRelease
1024
e: /Users/runner/work/BlueWallet/BlueWallet/node_modules/react-native-tor/android/src/main/java/com/reactnativetor/TorBridgeRequest.kt: (54, 59): Unresolved reference: create
1025

1026
e: /Users/runner/work/BlueWallet/BlueWallet/node_modules/react-native-tor/android/src/main/java/com/reactnativetor/TorBridgeRequest.kt: (55, 23): Using 'get(String): MediaType' is an error. moved to extension function
1027
> Task :react-native-tor:compileReleaseKotlin FAILED
1028
e: /Users/runner/work/BlueWallet/BlueWallet/node_modules/react-native-tor/android/src/main/java/com/reactnativetor/TorBridgeRequest.kt: (58, 48): Using 'get(String): MediaType' is an error. moved to extension function
1029
w: Detected multiple Kotlin daemon sessions at build/kotlin/sessions
1030
e: /Users/runner/work/BlueWallet/BlueWallet/node_modules/react-native-tor/android/src/main/java/com/reactnativetor/TorBridgeRequest.kt: (79, 16): Using 'headers(): Headers' is an error. moved to val
1031

1032
e: /Users/runner/work/BlueWallet/BlueWallet/node_modules/react-native-tor/android/src/main/java/com/reactnativetor/TorBridgeRequest.kt: (84, 31): Using 'code(): Int' is an error. moved to val
1033
Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
1034
e: /Users/runner/work/BlueWallet/BlueWallet/node_modules/react-native-tor/android/src/main/java/com/reactnativetor/TorBridgeRequest.kt: (88, 27): Using 'body(): ResponseBody?' is an error. moved to val
1035
Use '--warning-mode all' to show the individual deprecation warnings.
1036
e: /Users/runner/work/BlueWallet/BlueWallet/node_modules/react-native-tor/android/src/main/java/com/reactnativetor/TorBridgeRequest.kt: (99, 20): Using 'code(): Int' is an error. moved to val
1037
See https://docs.gradle.org/6.9.1/userguide/command_line_interface.html#sec:command_line_warnings
1038
e: /Users/runner/work/BlueWallet/BlueWallet/node_modules/react-native-tor/android/src/main/java/com/reactnativetor/TorModule.kt: (90, 25): Type mismatch: inferred type is (???, ???) -> Boolean but HostnameVerifier was expected
1039
544 actionable tasks: 544 executed
1040
e: /Users/runner/work/BlueWallet/BlueWallet/node_modules/react-native-tor/android/src/main/java/com/reactnativetor/TorModule.kt: (90, 27): Cannot infer a type for this parameter. Please specify it explicitly.
1041
e: /Users/runner/work/BlueWallet/BlueWallet/node_modules/react-native-tor/android/src/main/java/com/reactnativetor/TorModule.kt: (90, 30): Cannot infer a type for this parameter. Please specify it explicitly.
1042

1043
FAILURE: Build failed with an exception.
1044

1045
* What went wrong:
1046
Execution failed for task ':react-native-tor:compileReleaseKotlin'.
1047
> Compilation error. See log for more details

**Comment by gabidi** [comment]
[this branch](https://github.com/Sifir-io/react-native-tor/commits/feat/hs_jsi) is WIP to convert the repo from using the bridge to JSI (should resolve most android issues). 
last two commits resolve RN 65,66 issues reported here.
I'll try to make some time this weekend to  just merge the relevant commits into main for you guys.

**Comment by kaloudis** [comment]
@gabidi lmk if there's anything I could do to assist here

**Comment by marcosrdz** [comment]
Any updates on this issue?

**Comment by gabidi** [comment]
Should be resolved in https://github.com/Sifir-io/react-native-tor/pull/44
