### ISSUE TITLE
[TcpConnection ] Socket Usage Example - Lack of server side code example

### ISSUE THREAD

**Issue by matetuh** [Sifir-io/react-native-tor#40]
Hello ✋  

in the Socket Usage Example tab https://github.com/Sifir-io/react-native-tor#socket-usage-example, only the client side tcp connection code example is shown. Can you provide an example of server-side code that is able to handle queries sent to the server from a client? Or can you write what package to use to handle these queries?

**Additionally**, I think I found a bug in the README. Because in the folder 'example / src / App.test.tsx' https://github.com/Sifir-io/react-native-tor/blob/main/example/src/App.test.tsx the method 'createTcpConnection ()' (120 lines of code) is called from the variable 'client' which is the function 'TorBridge ()' (6 lines of code). In README however, the method 'createTcpConnection ()' is called from the variable 'tor' which is a function 'Tor ()'. Is this a bug? Because i tried the code and only the one from example works.

**Example TCP connection in react-native-tor:**
-**example/src/App.test.tsx**
![image](https://user-images.githubusercontent.com/47751476/142779036-233551a4-d72b-4211-b674-826e7b1faa6d.png)
![image](https://user-images.githubusercontent.com/47751476/142779041-8e47a02e-d905-4c98-8766-36bac87db29d.png)
-**README**
![image](https://user-images.githubusercontent.com/47751476/142778978-d0453552-18b6-423e-8cf1-b3d2bc6dfde0.png)

Thanks 👍

**Comment by gabidi** [comment]
Hi,
1. A TCP socket Example depends  on the language you're using but any standard socket server would work (ex: [Node.js net ](https://nodejs.org/api/net.html) ), just make sure the data emitted is new line delineated, from `README.md`:
```The current TcpStream implementation emits per line of data received. That is it reads data from the socket until a new line is reached, at which time it will emit the string line received (by calling onData(data,null)

    Ergo sum the current implementation is only suited for text data that is line delineated (Electrum server, etc..)
    Future implementations will support constant streams of buffered base64 data.
```
2. Not sure I understand what the bug being referenced is....

**Comment by matetuh** [comment]
Hi,
1. Is it possible for you to present the server code used in the example 'example / src / App.test.tsx' ? 

In the example there is an onion link that you can connect to via tcp and I tested this example and it works. I would just like to see an example of handling these inquiries from tcp tor.
![image](https://user-images.githubusercontent.com/47751476/143036153-aa660c3d-1d77-4245-899f-592db960d0c2.png)

2. As for the bug, I wonder if the README should not be updated with the code from the 'example / src / App.test.tsx'.

Thank you for your reply! 👍
