### ISSUE TITLE
Unable to create aab when using this package

### ISSUE THREAD

**Issue by Idan-Neeman** [Sifir-io/react-native-tor#41]
BlueWallet use this package, and I notice that when I try to build bundle I got problems.

I execute the command:
`./gradlew bundleRelease`
but I get at the end of the process error:
`Unrecognized native architecture for directory 'lib/arm64'.`

If I try to build APK with:
`./gradlew assembleRelease`
It works without error, but it's not really helping me.

I saw that when I remobe the implementation of aar from the build gradle file the build success, I guess there is problem with handle of so files for arm64.
Someone can help me?

**Comment by Overtorment** [comment]
why is this ticket closed?

related: https://github.com/BlueWallet/BlueWallet/issues/4235
