### ISSUE TITLE
Bump iOS min version to 11.1

### ISSUE THREAD

**Issue by gabidi** [Sifir-io/react-native-tor#6]
Tor binary coming from Sifir-rs-sdk isn't compiled for Apple's 32-bit targets (<ios11)
see:
https://blog.rust-lang.org/2020/01/03/reducing-support-for-32-bit-apple-targets.html#which-targets-are-affected

Which means iphone4 and less won't be able to use this lib 
https://developer.apple.com/support/required-device-capabilities/

Will bump up podspec to ios11 and update readme.

**Comment by gabidi** [comment]
Also Build Settings > Build Options > Enable Bitcode` to `No` for both Debug and Release.

**Comment by marcosrdz** [comment]
https://github.com/Sifir-io/react-native-tor/pull/7

**Comment by gabidi** [comment]
Resolved by fd3ec874af7281fa886a3150a0cdcbbdf2594668 and #7
