### ISSUE TITLE
Libsifir_ios.framework/Libsifir_ios Bitcode

### ISSUE THREAD

**Issue by marcosrdz** [Sifir-io/react-native-tor#8]
When trying to compile an app on release mode, the following error is shown:

ld: '/Users/runner/work/1/s/node_modules/react-native-tor/ios/Libsifir_ios.framework/Libsifir_ios' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. file '/Users/runner/work/1/s/node_modules/react-native-tor/ios/Libsifir_ios.framework/Libsifir_ios' for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by gabidi** [comment]
Hi,
This is a known issue. From readme:
```
iOS Projects note:

    iOS 11.1 > only: Support iOS Version is 11.1 and higher (#6)
    Bitcode not supported: Set Build Settings > Build Options > Enable Bitcode to No for both Debug and Release.
```
Is it failing even after doing the above ?

**Comment by Overtorment** [comment]
but isnt bitcode a good thing..?

![image](https://user-images.githubusercontent.com/1913337/103015335-253a6080-4538-11eb-97d6-b3498a981ef1.png)
https://developer.apple.com/documentation/xcode/reducing_your_app_s_size/doing_basic_optimization_to_reduce_your_app_s_size

**Comment by marcosrdz** [comment]
> Hi,
> 
> This is a known issue. From readme:
> 
> ```
> 
> iOS Projects note:
> 
> 
> 
>     iOS 11.1 > only: Support iOS Version is 11.1 and higher (#6)
> 
>     Bitcode not supported: Set Build Settings > Build Options > Enable Bitcode to No for both Debug and Release.
> 
> ```
> 
> Is it failing even after doing the above ?

Yes. It is. Can be reproduced on Release mode.

**Comment by gabidi** [comment]
@Overtorment  Rust-iOS compilation issues with generating Bitcode that is compatible with Apple's version of it.
@marcosrdz  That's strange, turning off Bitcode in the project for *Release* should not give you problems.

**Comment by marcosrdz** [comment]
Just took another look. pod install was resetting the react-native-tor Pods project target to ENABLE_BITCODE='YES'. I had to add this to my Podfile:

  if ['react-native-tor'].include? target.name 
              config.build_settings['ENABLE_BITCODE'] = 'NO'
           end
