### ISSUE TITLE
ITMS-90535: Unexpected CFBundleExecutable Key - The bundle at '/Payload/app.app/Frameworks/Libsifir_ios.framework/Resources/Info.plist' does not contain a bundle executable.

### ISSUE THREAD

**Issue by 4l3ss** [Sifir-io/react-native-tor#9]
Hi, when submitting my app to testflight I got this message from Apple.
I'm not sure what it means or how to fix it.

> ITMS-90535: Unexpected CFBundleExecutable Key - The bundle at '/Payload/app.app/Frameworks/Libsifir_ios.framework/Resources/Info.plist' does not contain a bundle executable. If this bundle intentionally does not contain an executable, consider removing the CFBundleExecutable key from its Info.plist and using a CFBundlePackageType of BNDL. If this bundle is part of a third-party framework, consider contacting the developer of the framework for an update to address this issue.

Thank you

**Comment by gabidi** [comment]
Yep that's an issue i'm literally working on today, some bugs you have to go through the whole process of submission before Apple well let you find out :/

**Comment by 4l3ss** [comment]
Thanks a lot. If that helps, after some trial and error I managed to make it work by simply removing the file Libsifir_ios.framework/Resources/Info.plist in node_modules.
I'm not sure if that's the correct thing to do tho

**Comment by gabidi** [comment]
Yeah what's confusing is Apple specifically ask you to add the `Info.plist` under Resources, but the Framework won't compile if you do so :/ 
https://developer.apple.com/library/archive/documentation/MacOSX/Conceptual/BPFrameworks/Concepts/FrameworkAnatomy.html

**Comment by gabidi** [comment]
I merged a fix that essentially just removes plist from resources. Test flight seem to be working and based on your feedback that works too.
Will close this now.
